##
## EPITECH PROJECT, 2022
## B-YEP-410-PAR-4-1-zappy-thomas.willson
## File description:
## Makefile
##

all:
	(cd ai && make)
	(cd server && make)
	(cd gui && make)

clean:
	(cd ai && make fclean)
	(cd server && make fclean)
	(cd gui && make fclean)

fclean:	clean

re:	fclean all

.PHONY:	all clean fclean re
